---
- name: Configure APT sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list
  notify: apt update

- name: Configure apt.conf
  template: src=apt.conf.j2 dest=/etc/apt/apt.conf
  notify: apt update

