---
- name: Install common packages
  apt: pkg=$item state=latest
  with_items:
    - tmux
    - zsh
    - git
    - wget
    - vim-nox
    - lsb-release
    - less
    - exuberant-ctags
    - ca-certificates

- name: Set root shell to zsh
  user: name=root shell=/usr/bin/zsh

- name: Install dotfiles
  git: repo=https://github.com/philpep/dotfiles dest=/root/dotfiles
       force=no update=no
  register: dotfiles

- name: Install submodule
  command: chdir=/root/dotfiles git submodule {{ item }}
  with_items:
    - init
    - update
  when: dotfiles.changed

- name: Setup dotfiles links
  command: chdir=/root/dotfiles bash install.sh
  when: dotfiles.changed

- name: Install vim plugins
  command: vim +BundleInstall +qall
  when: dotfiles.changed

- name: Copy ssh keys
  authorized_key: user=root key="{{ lookup('file', item) }}"
  with_items:
    - bezout.pub
    - backup.pub
    - shen.pub
